# Server port
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://thuandeptrai123:thuandeptrai@cluster0.pqwfiiv.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=qlsdb

# App name
spring.application.name=qlsapi

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
