name: CI/CD Docker Hub

on:
  push:
    branches: [ "main" ] # Kiểm tra xem nhánh của ông là 'main' hay 'master' nhé

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend        # Chỗ này cực kỳ quan trọng: trỏ vào thư mục backend
          file: ./backend/Dockerfile # Chỉ định chính xác file Dockerfile nằm ở đâu
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-spring-boot-app:latest
